---
- name: Install lighttpd server and python requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - lighttpd
    - python3-full
    - python3-virtualenv

- name: Ensure lighttpd is enabled
  ansible.builtin.systemd:
    name: lighttpd.service
    state: started
    enabled: true

- name: Configure lighttpd
  ansible.builtin.template:
    src: lighttpd.conf.jinja2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart lighttpd

- name: Install ansible-cmdb pip module
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-cmdb
    # virtualenv: "{{ lookup('env', 'HOME') }}/.local"
    virtualenv: "{{ lookup('env', 'HOME') }}/{{ html_inventory_venv_subdir }}"
  become: true
  become_user: "{{ html_inventory_user_name }}"

- name: Ensure ~/.local/bin/ exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/"
    state: directory
    owner: "{{ html_inventory_user_name }}"
    group: "{{ html_inventory_user_name }}"
    mode: "0770"
  become: true
  become_user: "{{ html_inventory_user_name }}"

- name: Link some useful bind from venv to ~/.local/bin/
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/{{ html_inventory_venv_subdir }}/bin/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/{{ item }}"
    state: link
    owner: "{{ html_inventory_user_name }}"
    group: "{{ html_inventory_user_name }}"
    follow: false
  loop:
    - ansible
    - ansible-cmdb
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ html_inventory_user_name }}"

- name: Ensuring html inventory creation script sudo permissions
  ansible.builtin.template:
    src: create-host-inventory.jinja2
    dest: "/etc/sudoers.d/create-host-inventory"
    owner: "root"
    group: "root"
    mode: "0640"
  become: true
  become_user: root

- name: Ensuring html inventory creation script
  ansible.builtin.template:
    src: create-host-inventory.sh.jinja2
    dest: "/usr/local/bin/create-host-inventory.sh"
    owner: "{{ html_inventory_user_name }}"
    group: "{{ html_inventory_user_name }}"
    mode: "0750"
  become: true
  become_user: root

- name: Copy html inventory service
  ansible.builtin.template:
    src: create-host-inventory.service.jinja2
    dest: /etc/systemd/system/create-host-inventory.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd to read the new systemd service
  become: true
  become_user: root

- name: Copy html inventory timer
  ansible.builtin.template:
    src: create-host-inventory.timer.jinja2
    dest: /etc/systemd/system/create-host-inventory.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd to read the new systemd service
  become: true
  become_user: root

- name: Enable html inventory timer
  ansible.builtin.systemd:
    name: create-host-inventory.timer
    enabled: true
    state: started
  become: true
  become_user: root
