---
- name: install lighttpd server and python requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - lighttpd
    - python3-full

- name: ensure lighttpd is enabled
  ansible.builtin.systemd:
    name: lighttpd.service
    state: started
    enabled: true

- name: configure lighttpd
  ansible.builtin.template:
    src: lighttpd.conf.jinja2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart lighttpd

- name: "ensuring script directory for {{ jump_host.user_name }}"
  ansible.builtin.file:
    path: "/home/{{ jump_host.user_name }}/scripts/"
    state: directory
    owner: "{{ jump_host.user_name }}"
    group: "users"
    mode: 0770

- name: install ansible-cmdb pip module
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-cmdb
    virtualenv: "/home/{{ jump_host.user_name }}/.local"
  become: true
  become_user: "{{ jump_host.user_name }}"

- name: ensuring html inventory creation script sudo permissions
  ansible.builtin.template:
    src: create-host-inventory.jinja2
    dest: "/etc/sudoers.d/create-host-inventory"
    owner: "root"
    group: "root"
    mode: 0640

- name: ensuring html inventory creation script
  ansible.builtin.template:
    src: create-host-inventory.sh.jinja2
    dest: "/home/{{ jump_host.user_name }}/scripts/create-host-inventory.sh"
    owner: "{{ jump_host.user_name }}"
    group: "users"
    mode: 0755

- name: copy html inventory service
  ansible.builtin.template:
    src: create-host-inventory.service.jinja2
    dest: /etc/systemd/system/create-host-inventory.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd to read the new systemd service

- name: copy html inventory timer
  ansible.builtin.template:
    src: create-host-inventory.timer.jinja2
    dest: /etc/systemd/system/create-host-inventory.timer
    owner: root
    group: root
    mode: 0644
  notify: reload systemd to read the new systemd service

- name: enable html inventory timer
  ansible.builtin.systemd:
    name: create-host-inventory.timer
    enabled: true
    state: started
